const nouns = [
  'A banana',
  'A fire',
  'A cat',
  'A dog',
  'A house',
  'A car',
  'A book',
  'A computer',
  'A tree',
  'A table',
  'A chair',
  'A mountain',
  'A river',
  'The sun',
  'The moon',
  'A star',
  'A flower',
  'A bird',
  'A child',
  'A heart',
  'A beach',
  'A cloud',
  'Snow',
  'The wind',
  'A bridge',
  'A road',
  'A ship',
  'An airplane',
  'A bicycle',
  'A shoe',
  'A phone',
  'A camera',
  'A guitar',
  'A painting',
  'A doctor',
  'A nurse',
  'A police officer',
  'A firefighter',
  'An artist',
  'A writer',
  'An actor',
  'An actress',
  'A singer',
  'A dancer',
  'A chef',
  'An engineer',
  'A scientist',
  'An athlete',
  'A baby',
  'Your neighbor',
  'A villain',
  'A king',
  'A queen',
  'A prince',
  'A princess',
  'A wizard',
  'A witch',
  'A monster',
  'A ghost',
  'A robot',
  'An alien',
  'A superhero',
  'A vampire',
  'A zombie',
  'A dragon',
  'A treasure',
  'A castle',
  'A fairy',
  'A unicorn',
  'A mermaid',
  'A pirate'
]

const actions = [
  'goes jogging',
  'is grocery shopping',
  'is racing',
  'reads a book',
  'watches a movie',
  'plays soccer',
  'cooks a meal',
  'sings a song',
  'dances',
  'paints a picture',
  'writes a poem',
  'takes a nap',
  'goes swimming',
  'travels to a new city',
  'attends a concert',
  'practices yoga',
  'plays video games',
  'climbs a mountain',
  'goes hiking',
  'visits a museum',
  'rides a bike',
  'listens to music',
  'meets a friend for coffee',
  'volunteers at a charity',
  'learns a new language',
  'watches a sunset',
  'takes a photograph',
  'plants a garden',
  'goes fishing',
  'writes in a journal',
  'solves a puzzle',
  'exercises at the gym',
  'watches a sports game',
  'attends a party',
  'practices meditation',
  'bakes cookies',
  'learns to play a musical instrument',
  'goes camping',
  'writes code',
  'goes to the theater',
  'visits a theme park',
  'tries a new recipe',
  'goes on a road trip',
  'reads the news',
  'attends a workshop',
  'watches a documentary',
  'goes to the beach',
  'tries a new hobby',
  'takes a bike ride',
  'does volunteer work',
  'attends a yoga class',
  'goes on a picnic',
  'learns a new skill',
  'goes to a comedy show',
  'watches a sunrise',
  'explore a new trail',
  'attends a wedding',
  'starts a DIY project',
  'visits a historical site',
  'attends a fitness class',
  'goes to a karaoke night',
  'watches a theater performance',
  'plays board games',
  'goes stargazing',
  'writes a blog post',
  'tries a new sport',
  'goes to a farmers market',
  'takes a cooking class',
  'watches a wildlife documentary',
  'starts a book club',
  'goes on a sightseeing tour',
  'attends a photography workshop',
  'tries a new restaurant',
  'goes to a music festival',
  'creates a piece of art',
  'attends a cooking competition',
  'listens to a podcast',
  'goes to a dance class',
  'writes a short story',
  'participates in a charity run',
  'attends a painting workshop',
  'watches a fashion show',
  'goes on a nature walk',
  'tries a new workout routine',
  'practices mindfulness',
  'goes to a poetry reading',
  'attends a wine tasting',
  'watches a magic show',
  'takes a pottery class',
  'learns to knit',
  'goes to a science exhibition',
  'tries a new hairstyle',
  'attends a jewelry-making workshop'
]

export { nouns, actions }
